import 'package:flutter/material.dart';

const seed = Color(0xFFFFFFFF);

const lightColorScheme = ColorScheme(
	brightness: Brightness.light,
	primary : Color(0xFFFFFFFF),
	onPrimary : Color(0xFFFFFFFF),
	primaryContainer : Color(0xFFFFFFFF),
	onPrimaryContainer : Color(0xFFFFFFFF),
	secondary : Color(0xFFFFFFFF),
	onSecondary : Color(0xFFFFFFFF),
	secondaryContainer : Color(0xFFFFFFFF),
	onSecondaryContainer : Color(0xFFFFFFFF),
	tertiary : Color(0xFFFFFFFF),
	onTertiary : Color(0xFFFFFFFF),
	tertiaryContainer : Color(0xFFFFFFFF),
	onTertiaryContainer : Color(0xFFFFFFFF),
	error : Color(0xFFFFFFFF),
	errorContainer : Color(0xFFF9DEDC),
	onError : Color(0xFFFFFFFF),
	onErrorContainer : Color(0xFFFFFFFF),
	background : Color(0xFFFFFBFE),
	onBackground : Color(0xFFFFFFFF),
	surface : Color(0xFFFFFBFE),
	onSurface : Color(0xFFFFFFFF),
	surfaceVariant : Color(0xFFE7E0EC),
	onSurfaceVariant : Color(0xFFFFFFFF),
	outline : Color(0xFFFFFFFF),
	onInverseSurface : Color(0xFFF4EFF4),
	inverseSurface : Color(0xFFFFFFFF),
	inversePrimary : Color(0xFFFFFFFF),
	shadow : Color(0xFFFFFFFF),
);

const darkColorScheme = ColorScheme(
	brightness: Brightness.dark,
	primary : Color(0xFFFFFFFF),
	onPrimary : Color(0xFFFFFFFF),
	primaryContainer : Color(0xFFFFFFFF),
	onPrimaryContainer : Color(0xFFFFFFFF),
	secondary : Color(0xFFFFFFFF),
	onSecondary : Color(0xFFFFFFFF),
	secondaryContainer : Color(0xFFFFFFFF),
	onSecondaryContainer : Color(0xFFFFFFFF),
	tertiary : Color(0xFFFFFFFF),
	onTertiary : Color(0xFFFFFFFF),
	tertiaryContainer : Color(0xFFFFFFFF),
	onTertiaryContainer : Color(0xFFFFFFFF),
	error : Color(0xFFFFFFFF),
	errorContainer : Color(0xFFFFFFFF),
	onError : Color(0xFFFFFFFF),
	onErrorContainer : Color(0xFFFFFFFF),
	background : Color(0xFFFFFFFF),
	onBackground : Color(0xFFFFFFFF),
	surface : Color(0xFFFFFFFF),
	onSurface : Color(0xFFFFFFFF),
	surfaceVariant : Color(0xFFFFFFFF),
	onSurfaceVariant : Color(0xFFFFFFFF),
	outline : Color(0xFFFFFFFF),
	onInverseSurface : Color(0xFFFFFFFF),
	inverseSurface : Color(0xFFFFFFFF),
	inversePrimary : Color(0xFFFFFFFF),
	shadow : Color(0xFFFFFFFF),
);